#!/bin/bash

###############################################################################
##
## Quick navigation to domains on a DirectAdmin based webserver
## ============================================================
##
## Brief: Allows for fuzzy navigation towards domains on a DirectAdmin based
##        webserver
##
## Installation by adding an alias in the .bashrc file (Assuming binaries are
## in search path):
##   `alias go2site='. go2site'`
##
## Author: Koen Hausmans
##
###############################################################################

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. $BASEDIR/go2x -s=/home/clients/*/domains/ "$@"

