#!/bin/bash

###############################################################################
##
## Quick navigation to users on a DirectAdmin based webserver
## ==========================================================
##
## Brief: Allows for fuzzy navigation towards users on a DirectAdmin based
##        webserver
##
## Installation by adding an alias in the .bashrc file (Assuming binaries are
## in search path):
##   `alias go2user='. go2user'`
##
## Author: Koen Hausmans
##
###############################################################################

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. $BASEDIR/go2x -s=/home/clients/ "$@"

